
export interface Project {
    id: string;
      title: string;
        description: string;
          imageUrl: string; 
            category: string;
              year: string;
                gallery?: string[]; // Imágenes adicionales para el bucle del Hero (4 imágenes recomendadas)
                  videoUrl?: string; // Enlace opcional al vídeo o tráiler
                  }

                  /**
                   * LISTA COMPLETA DE TUS PROYECTOS
                    */
                    export const PROJECTS: Project[] = [
                      {
                          id: '1',
                              title: 'La Reina Urraca I de León',
                                  description: 'Una monarca desconocida que forjó la historia de la península.',
                                      imageUrl: 'https://firebasestorage.googleapis.com/v0/b/studio-2080727485-cb6a0.firebasestorage.app/o/urraca04.png?alt=media&token=79a2624f-34a2-4844-aad2-7a5247236a8b',
                                          category: 'Premiados',
                                              year: '2024',
                                                  videoUrl: 'https://www.youtube.com/watch?v=lMInJ0_KZro',
                                                      gallery: [
                                                            'https://firebasestorage.googleapis.com/v0/b/studio-2080727485-cb6a0.firebasestorage.app/o/urraca04.png?alt=media&token=79a2624f-34a2-4844-aad2-7a5247236a8b',
                                                                  'https://firebasestorage.googleapis.com/v0/b/studio-2080727485-cb6a0.firebasestorage.app/o/urraca01.png?alt=media&token=3f0ccf6f-d3c3-4bb9-a251-89bb2c3cf8f0',
                                                                        'https://firebasestorage.googleapis.com/v0/b/studio-2080727485-cb6a0.firebasestorage.app/o/urraca02.png?alt=media&token=02932aff-0027-4bf4-b032-1a0011e59001',
                                                                              'https://firebasestorage.googleapis.com/v0/b/studio-2080727485-cb6a0.firebasestorage.app/o/urraca03.png?alt=media&token=0c3a868e-ab15-4013-94b6-d712a8881131'
                                                                                  ]
                                                                                    },
                                                                                      {
                                                                                          id: '2',
                                                                                              title: 'Hanguk Sukje',
                                                                                                  description: 'Un recorrido en formato animación por Corea',
                                                                                                      imageUrl: 'https://firebasestorage.googleapis.com/v0/b/studio-2080727485-cb6a0.firebasestorage.app/o/hanguk%20sukje.png?alt=media&token=1fde94be-45e0-49ea-9da8-6132252e0dae',
                                                                                                          category: 'Premiados',
                                                                                                              year: '2025',
                                                                                                                  videoUrl: 'https://www.youtube.com/watch?v=swlxgdwNrxs'
                                                                                                                    },
                                                                                                                      {
                                                                                                                          id: '3',
                                                                                                                              title: 'PERSONA',
                                                                                                                                  description: 'Un relato de Ciencia Ficción esperanzador sobre el Alzheimer.',
                                                                                                                                      imageUrl: 'https://firebasestorage.googleapis.com/v0/b/studio-2080727485-cb6a0.firebasestorage.app/o/persona.png?alt=media&token=ae408d78-1a90-4b59-b345-250c877b7600',
                                                                                                                                          category: 'Premiados',
                                                                                                                                              year: '2025',
                                                                                                                                                  videoUrl: 'https://www.youtube.com/watch?v=RAi1pe2JhoU'
                                                                                                                                                    },
                                                                                                                                                      {
                                                                                                                                                          id: '4',
                                                                                                                                                              title: 'MiniVigo',
                                                                                                                                                                  description: 'Un recorrido a vista de pájaro por un Vigo en formato maqueta',
                                                                                                                                                                      imageUrl: 'https://firebasestorage.googleapis.com/v0/b/studio-2080727485-cb6a0.firebasestorage.app/o/MINIVIGO.png?alt=media&token=c13044fd-8b7c-4e3f-b00e-a73ab0b1fb5d',
                                                                                                                                                                          category: 'Premiados',
                                                                                                                                                                              year: '2026',
                                                                                                                                                                                  videoUrl: 'https://www.youtube.com/watch?v=xFl8lYqW-08'
                                                                                                                                                                                    },
                                                                                                                                                                                      {
                                                                                                                                                                                          id: '5',
                                                                                                                                                                                              title: 'El Bosque de Ayer',
                                                                                                                                                                                                  description: 'El Alzheimer como viaje ensoñado y solitario por la memoria',
                                                                                                                                                                                                      imageUrl: 'https://picsum.photos/seed/forest-memory/600/338', 
                                                                                                                                                                                                          category: 'Premiados',
                                                                                                                                                                                                              year: '2024',
                                                                                                                                                                                                                  videoUrl: 'https://youtu.be/zmdw8VeGVuk'
                                                                                                                                                                                                                    },
                                                                                                                                                                                                                      {
                                                                                                                                                                                                                          id: '6',
                                                                                                                                                                                                                              title: 'Right here',
                                                                                                                                                                                                                                  description: 'Un recorrido por la maravilla y diversidad del mundo y la humanidad.',
                                                                                                                                                                                                                                      imageUrl: 'https://firebasestorage.googleapis.com/v0/b/studio-2080727485-cb6a0.firebasestorage.app/o/right%20here.png?alt=media&token=0b4bb484-eb0e-4657-ae76-bd4e9ed8eaac',
                                                                                                                                                                                                                                          category: 'Te interesa ver',
                                                                                                                                                                                                                                              year: '2025',
                                                                                                                                                                                                                                                  videoUrl: 'https://www.youtube.com/watch?v=rWy_xbn-V1s'
                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                          id: '7',
                                                                                                                                                                                                                                                              title: '4 horas 24 minutos',
                                                                                                                                                                                                                                                                  description: 'Una reflexión sobre el uso del móvil basado en una carata a la directora del diario el País.',
                                                                                                                                                                                                                                                                      imageUrl: 'https://firebasestorage.googleapis.com/v0/b/studio-2080727485-cb6a0.firebasestorage.app/o/4%20horas%2024%20minutos.png?alt=media&token=fa4e0810-cd56-48f3-b13f-e80c36773acc',
                                                                                                                                                                                                                                                                          category: 'Te interesa ver',
                                                                                                                                                                                                                                                                              year: '2025',
                                                                                                                                                                                                                                                                                  videoUrl: 'https://www.youtube.com/watch?v=qDVrPnWof9k'
                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                          id: '8',
                                                                                                                                                                                                                                                                                              title: 'Humanity',
                                                                                                                                                                                                                                                                                                  description: 'Los rostros y la vida de las personas, recreadas con IA.',
                                                                                                                                                                                                                                                                                                      imageUrl: 'https://firebasestorage.googleapis.com/v0/b/studio-2080727485-cb6a0.firebasestorage.app/o/humanity.jpg?alt=media&token=04e9b730-00f4-4e66-a43d-0a82fcaebdfc',
                                                                                                                                                                                                                                                                                                          category: 'Te interesa ver',
                                                                                                                                                                                                                                                                                                              year: '2024',
                                                                                                                                                                                                                                                                                                                  videoUrl: 'https://www.youtube.com/watch?v=jqjjUJ3bdeE'
                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                          id: '9',
                                                                                                                                                                                                                                                                                                                              title: 'Fashionistas',
                                                                                                                                                                                                                                                                                                                                  description: 'Un temprano intento de recrear moda y estilo con IA.',
                                                                                                                                                                                                                                                                                                                                      imageUrl: 'https://firebasestorage.googleapis.com/v0/b/studio-2080727485-cb6a0.firebasestorage.app/o/fashionistas.jpg?alt=media&token=81ebca2b-9494-404e-b0f2-7a4df9c51a52',
                                                                                                                                                                                                                                                                                                                                          category: 'Te interesa ver',
                                                                                                                                                                                                                                                                                                                                              year: '2024',
                                                                                                                                                                                                                                                                                                                                                  videoUrl: 'https://www.youtube.com/watch?v=NPdYMEwBK9k'
                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                                                          id: '10',
                                                                                                                                                                                                                                                                                                                                                              title: 'The Mystics',
                                                                                                                                                                                                                                                                                                                                                                  description: 'Una prueba de traer a la vida personajes creados por el entonces nuevo modelo de imagen Mystic.',
                                                                                                                                                                                                                                                                                                                                                                      imageUrl: 'https://firebasestorage.googleapis.com/v0/b/studio-2080727485-cb6a0.firebasestorage.app/o/the%20mystics.jpg?alt=media&token=5606ca26-24cf-4c37-aa80-5a09b7f50b96',
                                                                                                                                                                                                                                                                                                                                                                          category: 'Te interesa ver',
                                                                                                                                                                                                                                                                                                                                                                              year: '2024',
                                                                                                                                                                                                                                                                                                                                                                                  videoUrl: 'https://www.youtube.com/watch?v=xbiNAYw4lEM'
                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                                                                                          id: '11',
                                                                                                                                                                                                                                                                                                                                                                                              title: 'A message from Lewis Hine',
                                                                                                                                                                                                                                                                                                                                                                                                  description: 'El fotógrafo Lewis Hine regresa a la vida para animar a los periodistas a denunciar el trabajo infantil.',
                                                                                                                                                                                                                                                                                                                                                                                                      imageUrl: 'https://firebasestorage.googleapis.com/v0/b/studio-2080727485-cb6a0.firebasestorage.app/o/AI%20message%20from%20photographer%20Lewis%20Hine.jpg?alt=media&token=6ead2a74-c337-4011-b804-2646430a5066',
                                                                                                                                                                                                                                                                                                                                                                                                          category: 'Cortometrajes sociales',
                                                                                                                                                                                                                                                                                                                                                                                                              year: '2025',
                                                                                                                                                                                                                                                                                                                                                                                                                  videoUrl: 'https://www.youtube.com/watch?v=h4e4FhM2oZs'
                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                                                                                                                          id: '12',
                                                                                                                                                                                                                                                                                                                                                                                                                              title: 'Silent Chains',
                                                                                                                                                                                                                                                                                                                                                                                                                                  description: 'La dura realidad e los niños que trabajan.',
                                                                                                                                                                                                                                                                                                                                                                                                                                      imageUrl: 'https://firebasestorage.googleapis.com/v0/b/studio-2080727485-cb6a0.firebasestorage.app/o/silent%20chains.jpg?alt=media&token=19477c81-9b9f-4c91-8da5-98d8859cb8ac',
                                                                                                                                                                                                                                                                                                                                                                                                                                          category: 'Cortometrajes sociales',
                                                                                                                                                                                                                                                                                                                                                                                                                                              year: '2025',
                                                                                                                                                                                                                                                                                                                                                                                                                                                  videoUrl: 'https://www.youtube.com/watch?v=3ir0_f257as'
                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                                                                                                                                                          id: '13',
                                                                                                                                                                                                                                                                                                                                                                                                                                                              title: 'Lewis Hine photographs',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  description: 'Trayendo a la vida fotografías de Lewis Hine.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      imageUrl: 'https://firebasestorage.googleapis.com/v0/b/studio-2080727485-cb6a0.firebasestorage.app/o/lewis%20hine.jpg?alt=media&token=87f477e3-ca1c-4383-8076-17f2cd86cae8',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          category: 'Cortometrajes sociales',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              year: '2025',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  videoUrl: 'https://www.youtube.com/watch?v=Vg09jr7IqB0'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          id: '14',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              title: 'WWII Memorial',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  description: 'Fotografías de la segunda guerra mundial cobran vida.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      imageUrl: 'https://firebasestorage.googleapis.com/v0/b/studio-2080727485-cb6a0.firebasestorage.app/o/WWII.jpg?alt=media&token=0035a51b-4f1b-4a69-8bf9-2fe12d446b04',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          category: 'Experimentos tempranos',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              year: '2024',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  videoUrl: 'https://www.youtube.com/watch?v=yAJ1KDIDDV4'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          id: '15',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              title: 'Liminal',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  description: 'Un juego con los espacios vacíos y la inquietud.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      imageUrl: 'https://firebasestorage.googleapis.com/v0/b/studio-2080727485-cb6a0.firebasestorage.app/o/lliminal.jpg?alt=media&token=5de9ce1a-a98b-4130-90a1-7345e361c44b',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          category: 'Experimentos tempranos',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              year: '2024',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  videoUrl: 'https://www.youtube.com/watch?v=OWNFmM4Y4Eo'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          id: '16',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              title: 'Showreel 1',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  description: 'Explorando las capacidades primigenis de la generación de vídeo desde imagen.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      imageUrl: 'https://firebasestorage.googleapis.com/v0/b/studio-2080727485-cb6a0.firebasestorage.app/o/showreel.jpg?alt=media&token=07ad9a5a-bcf7-4f3d-bb0e-648d31a1d60f',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          category: 'Experimentos tempranos',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              year: '2024',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  videoUrl: 'https://www.youtube.com/watch?v=pKcYkhorzaQ'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          id: '17',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              title: 'Showreel 2',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  description: 'Explorando las capacidades primigenis de la generación de vídeo desde texto.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      imageUrl: 'https://firebasestorage.googleapis.com/v0/b/studio-2080727485-cb6a0.firebasestorage.app/o/showreel2.jpg?alt=media&token=318cb1d1-28b8-4957-84da-4796757657c1',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          category: 'Experimentos tempranos',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              year: '2024',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  videoUrl: 'https://www.youtube.com/watch?v=IyF8VGToq24'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    export const CATEGORIES = Array.from(new Set(PROJECTS.map(p => p.category)));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
}